export const permissions = {
    PROCESS_CLAIMS:"Can process Claims",
    UPDATE_CLAIMS:"Can update Claims",
    DO_CLAIM_RESEARCH:"Can do Claim Research",
    CAN_SEE_REJECT_CLAIMS:"Can see Rejected Claims",
    CAN_SEE_REJECT_CLAIMS_DETAILS:"Can see Rejected Claims Details",
    CAN_SEE_CHECK_REQUEST_CLAIMS:"Can see Check Request",
    SEE_CLAIM_REPORTS_QUERIES:"Can see Claim Reports/Queries",
    SEE_PLAYER_SUPPORT:"Can see Player Support*",
    SEE_PLAYER_VERIFICATION:"Can see Player Verification Services",
    RESET_PLAYER_PASSWORD:"Can reset Player password",
    UNLOCK_PLAYER_ACCOUNT:"Can unlock Player account",
    ENABLE_PLAYER_SCANS:"Can enable Player scans",
    SEE_PLAYER_SERVICE_REPORTS:"Can see Player Service Reports",
    UPDATE_PLAYER:"Can Update Player Profile",
    SEE_CLAIM_SUPPORT:"Can see Claim Support*",
    CAN_SEE_TICKET_STATUS_CLAIMED_CLAIM_REPORT:"Can see Ticket Status Claimed Claim Report",
    CAN_SEE_DRAW_DATE_7_DAYS_CLAIM_REPORT:"Can see Draw Date 7 Days Claim Report",
    CAN_SEE_DRAW_DATE_30_DAYS_CLAIM_REPORT:"Can see Draw Date 30 Days Claim Report",
    CAN_SEE_CUSTOM_CLAIM_REPORT:"Can see Custom Claim Report",
    CAN_SEE_SYSTEM_SUPPORT:"Can see System*",
    CAN_SEE_PLAYER_TICKET_HISTORY:"Can see Player Ticket History",
    CAN_SEE_PLAYER_EVENT_HISTORY:"Can see Player Event History",
    CAN_SEE_USER_AUDIT_ACTIONS:"Can see User Audit Actions",
    CAN_ACCESS_SECURITY_MODULE:"Can access Security Module*",
    CAN_ACCESS_FREQUENT_CASHER_MODULE:"Can access Frequent Casher Module",
    CAN_ACCESS_FINANCE_PAYMENTS_MODULE:"Can access Finance & Payments module*",
    CAN_ACCESS_ANALYTICS_MODULE:"Can access Analytics module*",
    CAN_ACCESS_USER_MANAGEMENT:"Can access User Management*",
    CAN_CREATE_USER_ACCOUNT:"Can create User account",
    CAN_EDIT_USER_ACCOUNT:"Can edit User account",
    CAN_RESET_USER_PASSWORD:"Can reset User password",
    CAN_DEACTIVATE_USER_ACCOUNT:"Can deactivate User account",
    CAN_REACTIVATE_USER_ACCOUNT:"Can reactivate User account",
    CAN_DELETE_USER_ACCOUNT:"Can delete User account",
    CAN_ACCESS_ROLE_MANAGEMENT:"Can access Role Management*",
    CAN_UNLOCK_USER_ACCOUNT:"Can Unlock User account",
    CAN_ADD_ROLE:"Can add Role",
    CAN_EDIT_ROLE:"Can edit Role",
    CAN_DELETE_ROLE:"Can delete Role",
    CAN_UPDATE_PLAYER_SSN:"Can update Player SSN",
    CAN_CONFIRM_PLAYER_EMAIL:"Can confirm Player Email",
    CAN_ACCESS_SETTINGS:"Can access Settings*",
    CAN_SEE_MFA_BYPASS_RULES:"Can see MFA Bypass Rules",
    CAN_EDIT_MFA_BYPASS_RULES:"Can edit MFA Bypass Rules",
    CAN_VIEW_DOWNLOAD_ADMINISTRATOR_USER_GUIDE:"Can view/download Administrator User Guide",
    CAN_VIEW_DOWNLOAD_PLAYER_SUPPORT_USER_GUIDE:"Can view/download Player Support User Guide",
    CAN_VIEW_DOWNLOAD_ANDROID_APP_USER_GUIDE:"Can view/download Android App User Guide",
    CAN_VIEW_DOWNLOAD_TROUBLESHOOTING_GUIDE:"Can view/download Troubleshooting Guide",
    CAN_VIEW_DOWNLOAD_TECHNICAL_DOCUMENTATION:"Can view/download Technical Documentation",
    CAN_SEE_CLAIMS:"Can see Claims",
    CAN_SEE_CLAIM_DETAILS:"Can see Claim Details",
    CAN_SEE_CLAIM_W2G:"Can see Claim W2G Form",
    CAN_RESUBMIT_PAYMENT:"Can Resubmit Payment",
    CAN_SEE_ACH_ACTIVITY:"Can see ACH Activity",
    CAN_SEE_DAILY_RECONCILIATION:"Can see Daily Reconciliation Report",
    CAN_SEE_BATCH_REJECT_FILE_DETAILS:"Can see Batch/Reject file details",
    CAN_SEE_BATCH_MASKED_DETAIL:"Can see Batch Masked PII details",
    CAN_SEE_REJECT_MASKED_DETAIL:"Can see Reject Masked PII details",
    CAN_SEE_CLAIM_TRANSACTION_DETAILS:"Can see Claim Transaction History details",
    CAN_SEE_CLAIM_TRANSACTION_PII:"Can see Claim Transaction Account Information",
    CAN_SEE_E_SIGNATURE:"Can see E-Signature",
}

export const timeOfDayFormat = 'HH:mm';