export const UserActionCategory = {
    PAGE_VIEW: 'Page View',
    TAB_VIEW: 'Tab View',
    API_CALL: 'API Call',
    BUTTON_CLICK: 'Button Click',
    FILTER_RESULTS: 'Filter Results'
}

export const UserAction = {
    LOGIN:'Login',
    LOGOUT:'Logout',
    RESET_USER_PASSWORD:'Reset User Password',
    ADD_USER:'Add User',
    EDIT_USER:'Edit User',
    UPDATE_USER:'Update User',
    DEACTIVATE_USER:'Deactivate User',
    DELETE_USER:'Delete User',
    USER_AUDIT_HISTORY_PAGE:'User Audit History Page',
    USER_ACTION_HISTORY_SEARCH:'User Action History Search',
    EDIT_ROLE:'Edit Role',
    UPDATE_ROLE:'Update Role',
    DELETE_ROLE:'Delete Role',
    ADD_ROLE:'Add Role',
    SEARCH_PLAYER:'Search Player',
    PLAYER_DETAILS:'Player Details',
    UPDATE_PLAYER_PROFILE:'Update Player Profile',
    RESET_PLAYER_PASSWORD:'Reset Player Password',
    UNLOCK_PLAYER:'Unlock Player',
    LOCK_PLAYER:'Lock Player',
    VERIFY_PLAYER:'Verify Player',
    LAUNCH_EXPERIAN:'Launch Experian',
    TICKET_HISTORY:'Ticket History',
    EVENT_HISTORY:'Event History',
    SEARCH_TICKET_HISTORY:'Search Ticket History',
    PLAYER_REPORTS_LOCKED_ACCOUNTS:'Player Reports - Locked Accounts',
    PLAYER_REPORTS_IDOLOGY_FAILED_STATUS:'Player Reports - Idology Failed Status',
    PLAYER_REPORTS_NO_IDOLOGY_STATUS:'Player Reports - No Idology Status',
    CUSTOM_PLAYER_REPORT:'Custom Player Report',
    DOWNLOAD_PLAYER_REPORT:'Download Player Report',
    PRINT_PLAYER_REPORT:'Print Player Report',
    SEARCH_CLAIM:'Search Claim',
    READ_ONLY_CLAIM_DETAILS:'Read-Only Claim Details',
    UPDATE_CLAIM:'Update Claim',
    PLAYER_MAINTENANCE:'Player Maintenance',
    PLAYER_SERVICE_REPORTS:'Player Service Reports',
    CLAIM_SUPPORT:'Claim Support',
    PLAYER_SUPPORT:'Player Support',
    SYSTEM_DASHBOARD:'System Dashboard',
    USER_MANAGEMENT:'User Management',
    ROLE_MANAGEMENT:'Role Management',
    LOCK_UNLOCK_PLAYER:'Lock Unlock Player',
    FREQUENT_CASHER:'Frequent Casher',
    CONFIRM_PLAYER_EMAIL:'Confirm Player Email',
    VIEW_CLAIMS:'View Claims',
    CLAIM_DETAILS:'Claim Details',
    VIEW_PAYMENT_DETAILS:'View Payment Details',
    SUBMIT_PAYMENT_DETAILS:'Submit Payment',
    VIEW_W2G:"View W2G",
    ACH_ACTIVITY:"ACH Activity",
    ACH_BATCH_DETAILS:"ACH Batch Details",
    SHOW_BATCH_FILE_PII:"Show Batch File PII",
    SHOW_REJECT_FILE_PII:"Show Reject File PII",
    VIEW_REJECTED_CLAIMS:"View Rejected Claims Queue",
    VIEW_ESIGNAURE: "View E-Signature",
    VIEW_ESIGNAURE_FAILED: "View E-Signature Failed",
    VIEW_ESIGNAURE_EXPIRED: "View E-Signature Expired",

}